#!/bin/bash

# Path to the file where IP ranges are saved
IP_FILE="/etc/nginx/cloudflare_ip_range"

# URL API Cloudflare
CLOUDFLARE_API="https://api.cloudflare.com/client/v4/ips"

# File update logic
{
  echo "# Generated by script on $(date)"
  curl --silent --request GET --url "$CLOUDFLARE_API" --header 'Content-Type: application/json' | \
  jq -r '.result | .ipv4_cidrs[], .ipv6_cidrs[]' | while read -r ip; do
    echo "set_real_ip_from $ip;"
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$IP_FILE"

# Reload Nginx
nginx -s reload
